[workspace]
members = [
  "nft-voucher",
  "treasury"
]

# Isso é importante para resolver dependências corretamente no optimizer
resolver = "2"

[workspace.metadata.optimizer]
# Lista os contratos a serem otimizados
contracts = ["treasury"]
